-- Current opportunities imported from Ellie's two grant workbooks.
-- The original workbooks remain the source archive; these rows make the new
-- portal useful on first launch. Incomplete template rows were not imported.
INSERT INTO public.grant_opportunities
  (id, pod_id, name, funder, audience, owner_member_id, url, opens_on, deadline, amount, geography, eligibility, required_materials, focus_areas, status, notes, verified_on)
VALUES
  ('grant_sheet_01', 'pod_grants', 'HerRise MicroGrant', '', 'Small Businesses', (SELECT id FROM public.team WHERE name='Angeline Chan' AND deleted_at IS NULL LIMIT 1), 'https://www.hersuitespot.com/herrise-microgrant-application/', NULL, NULL, '1000.0', 'Must be a business registered in the United States.', 'For-profit, women-owned small businesses across a wide range of industries. Nonprofits, franchises, direct sellers, authorized resellers, and independent consultants are not eligible. Must be at least 51% woman-owned and have less than $1 million in annual gross revenue. There''s an emphasis on women in color and under-resourced women', '', ARRAY['For profit','Small Business','Women Owned','US based']::text[], 'Researching', 'Purpose: To provide microgrants that help under-resourced women entrepreneurs, especially women of color, grow community-impacting small businesses by offering financial support
Opens: Beginning of each month
Deadline: Last day of each month', '2026-08-23'::date),
  ('grant_sheet_02', 'pod_grants', 'Verizon Small Business Digital Ready Grant', '', 'Small Businesses', (SELECT id FROM public.team WHERE name='Angeline Chan' AND deleted_at IS NULL LIMIT 1), 'https://digitalready.verizonwireless.com/funding/details', NULL, NULL, '10000.0', 'United States, Puerto Rico, or the U.S. Virgin Islands.', 'For profit small businesses Must be a small business. Business owner must be 18 or older. Owners of multiple businesses may apply for only one business. Applicants have to register and complete any combination of two eligible courses or events anytime in 2026 to unlock the grant application. (afterwards applicants are eligible for the grants awarded throughout the year)', '', ARRAY['For profit','Small Business','US based']::text[], 'Researching', 'Purpose: To help small businesses grow by providing free business education, networking opportunities, and financial support through grants.
Opens: January 1st, 2026
Deadline: December 31st, 2026', '2026-08-23'::date),
  ('grant_sheet_03', 'pod_grants', 'National Association for the Self-Employed Growth Grants', '', 'Small Businesses', (SELECT id FROM public.team WHERE name='Angeline Chan' AND deleted_at IS NULL LIMIT 1), 'https://www.nase.org/become-a-member/member-benefits/business-resources/growth-grants', NULL, NULL, 'up to $4,000', 'United States', 'Self-employed individuals and small business owners who are NASE members in good standing. Must be an eligible NASE member (membership requirements vary by membership type). Applicants must be NASE members before applying. Applications are reviewed quarterly. Funds may be used for business expenses but cannot be used to pay existing debt or rent/mortgage payments.', '', ARRAY['For profit','Small Business','US based','Individual/Entrepreneur']::text[], 'Researching', 'Purpose: To help self-employed individuals and small business owners grow their businesses by providing funding for business development, expansion, and operational improvements.
Opens: Year Round
Deadline: Rolling (applications are reviewed quarterly)', '2026-08-23'::date),
  ('grant_sheet_04', 'pod_grants', 'Freed Fellowship Grant', '', 'Small Businesses', (SELECT id FROM public.team WHERE name='Angeline Chan' AND deleted_at IS NULL LIMIT 1), 'https://freedfellowship.com/', NULL, NULL, '$500 monthly grant; recipients are eligible for an additional $2,500 dollars end of the year grant', 'United States', 'Existing small businesses and entrepreneurs. Must own an existing business. One business owner is selected each month as a Freed Fellow. All applicants receive a business evaluation, a Freed Score with personalized feedback based on their 5C Framework, and two months of free mentorship in the Freed Studio community.', '', ARRAY['For profit','Small Business','US based','Individual/Entrepreneur']::text[], 'Researching', 'Purpose: To help small business owners grow successful, impactful businesses by providing funding, personalized feedback, mentorship, and access to an entrepreneurial community.
Opens: Year Round
Deadline: Rolling (monthly selection)', '2026-08-23'::date),
  ('grant_sheet_05', 'pod_grants', 'Awesome Foundation Grant', '', 'Small Businesses', (SELECT id FROM public.team WHERE name='Angeline Chan' AND deleted_at IS NULL LIMIT 1), 'https://www.awesomefoundation.org/en/submissions/new', NULL, NULL, '1000.0', 'Varies by chapter (69 chapters across 10 countries). Applicants should apply through their local chapter.', 'Individuals, entrepreneurs, nonprofits, and organizations with innovative or community-benefiting projects. No specific business size requirement. Grants are awarded monthly by independent local chapters. Funding is provided with no equity, ownership, or repayment required ("no strings attached"). Projects are evaluated by each chapter individually.', '', ARRAY['Nonprofit','For profit','Individual/Entrepreneur']::text[], 'Researching', 'Purpose: To support innovative, creative, and community-focused projects by providing no strings attached funding to help bring ideas to life.
Opens: Year Round
Deadline: Rolling (varies by chapter; awards grants every month)', '2026-08-23'::date),
  ('grant_sheet_06', 'pod_grants', 'Hello Alice Funding Opportunities', '', 'Small Businesses', (SELECT id FROM public.team WHERE name='Angeline Chan' AND deleted_at IS NULL LIMIT 1), 'https://www.helloalice.com/small-business-grants-and-funding', NULL, NULL, 'Varies based on funding opportunity', 'Primarily United States', 'Small businesses and entrepreneurs (varies by funding opportunites) Varies by funding opportunity Applicants create a hello alice account and complete a business profile. The platform matches businesses with grants, accelerators, and funding opportunites. New funding programs are added throughout the year.', '', ARRAY['Small Business','Individual/Entrepreneur','US based']::text[], 'Researching', 'Purpose: To help small business owners discover and access funding, grants, accelerators, and other growth resources by matching them with opportunities based on their business profile.
Opens: Year Round
Deadline: Rolling (varies based on funding opportunity)', '2026-08-23'::date),
  ('grant_sheet_07', 'pod_grants', 'Innovation Matching Grants Program', '', 'Small Businesses', (SELECT id FROM public.team WHERE name='Angeline Chan' AND deleted_at IS NULL LIMIT 1), 'https://esd.ny.gov/innovation-matching-grants-program#how-to-apply', NULL, NULL, 'Up to $100,000 (Phase I) or $200,000 (Phase II), not exceeding 50% of the federal award', 'Must operate and be headquartered in New York State.', 'Small businesses applying for or receiving a federal SBIR or STTR award. Must be independently owned, not dominant in its field, and employ 100 or fewer employees. Applicants must be applying for or have recently received a SBIR/STTR award. Grant funds support commercialization expenses. Businesses must remain operating in New York for at least two years after successful commercialization.', '', ARRAY['For profit','Small Business']::text[], 'Researching', 'Purpose: To help New York small businesses develop and commercialize innovative technologies by providing matching funds for federal SBIR and STTR grants.
Opens: Second Wednesday in April and October (9:00 AM ET)
Deadline: One week after opening (the following Tuesday at 5:00 PM ET)', '2026-08-23'::date),
  ('grant_sheet_08', 'pod_grants', 'Neighborhood Business Grant (CitizensNYC)', '', 'Small Businesses', (SELECT id FROM public.team WHERE name='Angeline Chan' AND deleted_at IS NULL LIMIT 1), 'https://www.citizensnyc.org/nbg/', NULL, NULL, 'Up to $5,000', 'Must be located in one of New York City''s five boroughs.', 'Profit-generating small businesses. Must have been operating for at least two years and have 10 or fewer employees. Applicants must provide proof of business (such as tax documents or bank statements). Grants fund initiatives that positively impact the local community, and applications are evaluated based on need, relevance, urgency, and quality-of-life impact.', '', ARRAY['For profit','Small Business','NYC based']::text[], 'Researching', 'Purpose: To support neighborhood small businesses that improve their local communities by funding community-focused initiatives and projects.
Opens: Twice yearly (Spring and Fall grant cycles)
Deadline: February 2 for the Spring cycle and July 27 for the Fall cycle in 2026', '2026-08-23'::date),
  ('grant_sheet_09', 'pod_grants', 'HYHK Storefront Improvement Grant Program', '', 'Small Businesses', (SELECT id FROM public.team WHERE name='Angeline Chan' AND deleted_at IS NULL LIMIT 1), 'https://www.surveymonkey.com/r/T3RN62W', NULL, NULL, 'Up to $4,000', 'Must be located within the Hudson Yards Hell''s Kitchen (HYHK) district in New York City.', 'Storefront small businesses. Must have been operating for at least one year. This is a matching reimbursement grant. Businesses must obtain the required NYC Department of Buildings permits and use a licensed sign or awning installer.', '', ARRAY['For profit','Small Business','NYC based']::text[], 'Researching', 'Purpose: To help small businesses enhance their storefronts by providing matching grants for signage, awnings, and façade improvements that improve the appearance and vitality of the neighborhood.
Opens: Varies annually (2026 application period was open until April 15, 2026)
Deadline: April 15, 2026 (for the 2026 grant cycle)', '2026-08-23'::date),
  ('grant_sheet_10', 'pod_grants', 'ShopHand Small Business Boost Grant', '', 'Small Businesses', (SELECT id FROM public.team WHERE name='Angeline Chan' AND deleted_at IS NULL LIMIT 1), 'https://www.shophand.com/small-business-boost-grant', NULL, NULL, '$5,000 ($2,500 cash grant and $2,500 in ShopHand technical support/services)', 'United States', 'For-profit small businesses based in the United States. Must have fewer than 50 employees and annual revenue under $5 million. Winners receive both funding and technical support to help improve business operations.', '', ARRAY['For profit','Small Business','US based']::text[], 'Researching', 'Purpose: To help small business owners overcome technology and operational challenges by providing financial support and resources to improve business growth.
Opens: Varies (awarded three times per year)
Deadline: August 1, 2026 (current application period)', '2026-08-23'::date),
  ('grant_sheet_11', 'pod_grants', 'StartUP! Business Plan Competition. @NYC Public Library w/ Wells Fargo', '', 'Small Businesses', (SELECT id FROM public.team WHERE name='Emily Sotelo' AND deleted_at IS NULL LIMIT 1), 'https://www.nypl.org/business/events/new-york-startup-business-plan-competition :Manhattan/Staten Island. https://www.bklynlibrary.org/calendar/2026-powerup-business-central-library-business-20260402-0630pm : Brooklyn. https://queensstartup.org : Queens  . https://www.bxedc.org/bx-factor-2026 : Bronx', NULL, NULL, 'First place: $15,000. Second place: ~$10,000. Third PLace: $7,500', 'Must operate in 5 boroughs. Must maintain primary, legal residence in 5 boroughs', 'For profit only. Non profit orgs are no elgibile to enter. Businesses are start-up. Only if revenue earned less $10,000. Exceed $10,000 disqualifed all individual applicants must be 18+. Must attend an official online NYPL orientation session. Virtual workshops: attend 4 virtual training workshops in library nearby. Only one business plan per cycle', '', ARRAY['For profit','Small Business','US based']::text[], 'Researching', 'Purpose: Supporting NY entrepreneuers with cash prizes and practicial insights on how to grow a startup idea
Opens: Varies on borough.Manhattan/staten island (open late winter) . Brooklyn(April 2, 2026) Quuens (Jan 27,2026) Bronx (Feb 6,2026)
Deadline: Manhattan/staten island: June 10:11:59 pm. Brooklyn: May 4. Queens (March 2, 2026 11:59 PM EST). Bronx: March 6,2026', '2026-08-23'::date),
  ('grant_sheet_12', 'pod_grants', 'SBA WBC Modernization Initiative FY26', '', 'Small Businesses', (SELECT id FROM public.team WHERE name='Maitri Sharma' AND deleted_at IS NULL LIMIT 1), 'https://apply07.grants.gov/apply/jsf/workspace/createWorkspace.faces?activityID=CreateWorkspace&cleanSession=1&oppId=363154', '2026-07-06'::date, '2026-08-10'::date, '250000.0', '', 'Nonprofits having a 501(c)(3) status with the IRS, other than institutions of higher education', '', ARRAY['Non profit 501c']::text[], 'Researching', 'Purpose: To invite proposals for funding to establish a Women’s Business Centers (WBCs) modernization and alignment initiative. This initiative will establish a Lead Center Model, supported by a network of Service Centers, to deliver coordinated, statewide or territory-wide business services.', '2026-08-23'::date),
  ('grant_sheet_13', 'pod_grants', 'The Amber Grant', '', 'Small Businesses', (SELECT id FROM public.team WHERE name='Maitri Sharma' AND deleted_at IS NULL LIMIT 1), 'https://ambergrantsforwomen.com/get-an-amber-grant/apply-now/', NULL, '2026-08-31'::date, '', '', 'Female Business Owner', '', ARRAY['Women Owned']::text[], 'Researching', 'Purpose: to honor the memory of a very special young woman, Amber Wigdahl', '2026-08-23'::date),
  ('grant_sheet_14', 'pod_grants', 'NYC Cultural Development Fund (DCLA)', '', 'Small Businesses', (SELECT id FROM public.team WHERE name='Emily Sotelo' AND deleted_at IS NULL LIMIT 1), 'nyc.gov/site/dcla/cultural-funding', NULL, NULL, 'Varies. Small orgs-large insituions.', 'Operate in 5 boroughs', 'Nonprofit arts/cultural org or nonprofit with arts/culture in broader mission No hard business size required. Small orgs can use simplief treasuer''s statement must be compliant with NYS Charities Bureau + other non profit filing requirements. Past reporting non-complaince disqualifies', '', ARRAY['Nonprofit','NYC based']::text[], 'Researching', 'Purpose: City funding for public-facing arts & culture programming city-wide
Opens: FY26 already launched. FY28 opens 2027.
Deadline: FY27 deadline passed in April 2,2026. FY28 window opens in 2027.', '2026-08-23'::date),
  ('grant_sheet_15', 'pod_grants', 'Youth Service Capacity Building Grants (William T. Grant Foundation)', '', 'Small Businesses', (SELECT id FROM public.team WHERE name='Emily Sotelo' AND deleted_at IS NULL LIMIT 1), 'wtgrantfoundation.org/funding/youth-service-capacity-building-grants', NULL, NULL, 'Up to $60,000', '5 boroguhs of NYC', 'Nonprofits providing direct services to youth Small non profits (capacity building focus NOT large orgs.) Ages 5-25. Prior YSCG/YSG grantees must wait 18 months post-award before reapplying', '', ARRAY['NYC based','Nonprofit']::text[], 'Researching', 'Purpose: Strengthen internal systems/capacity of small youth-serving non profits
Opens: Applications are now open for the 2026 cycle.
Deadline: Sep 17, 2026 at 3:00 pm ET', '2026-08-23'::date),
  ('grant_sheet_16', 'pod_grants', 'NYC Green fund Grassroots Grant', '', 'Small Businesses', (SELECT id FROM public.team WHERE name='Emily Sotelo' AND deleted_at IS NULL LIMIT 1), 'cityparksfoundation.org/nycgreenfund', NULL, NULL, 'Orgs w total expenses between $0-$9,999 may apply up to $2,500. orgs $10,000 or higher apply for up to 25% of their annual operating budget MAX $40,000', 'all 5 boroughs', '501(3)(c) org or group utilizing fiscal spinder. LLC + 501(c)(4) not elgibile business size is determined by annual operating budget + directly affects how much you can receive:$0-$9,999: $2,500 $10,000-$174,999 annual budget->elgibile for up to 25% of annual budget. $175,000 + X grassroots grant Deadline is Aug 14.', '', ARRAY['NYC based','Non profit 501c']::text[], 'Researching', 'Purpose: Supports grassroots iniatives in NYC parks/open spaces. COMMUNITY ENGAGEMENT + environment stewardship. Gives funding to projects that are focused on youth development, health/wellness/arts/org capacity building
Opens: Applications are now open for the 2026 cycle.
Deadline: Friday, Agust 14, 2026 11:59 PM EST', '2026-08-23'::date),
  ('grant_sheet_17', 'pod_grants', 'Costco Wholesale Charitable Contributions Grants', '', 'Small Businesses', (SELECT id FROM public.team WHERE name='Emily Sotelo' AND deleted_at IS NULL LIMIT 1), 'costco.com', NULL, NULL, 'Varies.', 'located near a costco', 'Must be 501(3)(c)non progs + public schools located near a costco. No specific business size required. Limits grant to no more than 10% of your total program budget warehouse donations are most accessible. smallers contributions can be in the form of Costco Chop cards that can help support local events. Can either sign up online or in person', '', ARRAY['Non profit 501c']::text[], 'Researching', 'Purpose: Costcos'' charitable efforts focus on programs supporting children, education, health + human services in community where they do business and strengthen community
Opens: Open year round
Deadline: No fixed deadline. Applications are reviewed 4-6 weeks', '2026-08-23'::date),
  ('grant_sheet_18', 'pod_grants', 'Skip Grants', '', 'Small Businesses', (SELECT id FROM public.team WHERE name='Emily Sotelo' AND deleted_at IS NULL LIMIT 1), 'helloskip.com', NULL, NULL, 'Instant grants (small), monthly grants + larger $10,000 awards', 'United States', 'For-profit business Any size requires a skip platform memebership. Free tier avaliable but some grants are plus/pro memebers only', '', ARRAY['US based','For profit']::text[], 'Researching', 'Purpose: direct funding for entreprenurs + website that has other links for other grants
Opens: Rolling. Instant grants run roughly twice weekly
Deadline: Varies by grant. Instant grants have midweek deadlines', '2026-08-23'::date),
  ('grant_sheet_19', 'pod_grants', 'Breva Thrive Grant', '', 'Small Businesses', (SELECT id FROM public.team WHERE name='Emily Sotelo' AND deleted_at IS NULL LIMIT 1), 'breva.com', '2026-07-31'::date, '2026-10-31'::date, '5000.0', 'U.S', 'For profit w/ demonstrable community # Small. Must alr generate some amount of revenue Good for neighborhodshopps that sponser teams, host community events or feed ppl', '', ARRAY['US based','Small Business','For profit']::text[], 'Researching', 'Purpose: supporting businesses making a measurable community impact', '2026-08-23'::date),
  ('grant_sheet_20', 'pod_grants', 'The Pollination Project Daily Grant', '', 'Novus', (SELECT id FROM public.team WHERE name='Dinara Gargu' AND deleted_at IS NULL LIMIT 1), 'https://thepollinationproject.org/funding-eligibility/', NULL, NULL, 'up to $500', '', 'Volunteer-led individuals/groups/nonprofits; no paid staff; project budget under $10K; annual org budget under $50K; project must serve a charitable community purpose.', 'Online application; project description/goals, community impact, project plan, itemized budget; parent/guardian info if under 18. No EIN or financial report listed.', '{}'::text[], 'Researching', 'Opens: Rolling/year round', '2026-08-23'::date),
  ('grant_sheet_21', 'pod_grants', 'AwesomeNYC grant', '', 'Novus', (SELECT id FROM public.team WHERE name='Dinara Gargu' AND deleted_at IS NULL LIMIT 1), 'https://www.awesomefoundation.org/submissions/new?chapter=nyc', NULL, NULL, '1000.0', '', '$1000 grant; no requirements to apply ; Use the $1,000 to expand Volta NYC’s student-led consulting services for NYC small businesses, funding website/domain costs, digital tools, marketing materials, and other resources needed to provide free technology, finance, and marketing support to local businesses.', 'Name/email, project title, project description, how funds will be used, short applicant bio. Project website and up to 5 images are optional. No EIN or financial report listed.', '{}'::text[], 'Researching', 'Opens: Application deadline is the last day of every month', '2026-08-23'::date),
  ('grant_sheet_22', 'pod_grants', 'Karma for Cara Foundation Youth Microgrant', '', 'Novus', (SELECT id FROM public.team WHERE name='Dinara Gargu' AND deleted_at IS NULL LIMIT 1), 'Walmart Spark Good | Walmart.com', NULL, NULL, '$250–$1,000', '', 'U.S.-based youth-led service project; applicant must be 18 or younger; student groups are eligible; project must involve other youth and benefit the community; funding request $250–$1,000.', 'Online application; student/group contact info, project details, number of youth involved/people served, requested funding and project budget. Selected applicants may be interviewed. No EIN or financial report listed.', '{}'::text[], 'Researching', 'Opens: Always open / applications accepted year-round
Deadline: nearest close date: October 1, 2026 at 11:59 PM ET', '2026-08-23'::date),
  ('grant_sheet_23', 'pod_grants', 'Walmart Spark Good Local Grants', '', 'Novus', (SELECT id FROM public.team WHERE name='David Grinberg' AND deleted_at IS NULL LIMIT 1), 'Spark Good Local Grants Guidelines', '2026-08-01'::date, '2026-11-30'::date, '$250 - $5000', '', '501(c)(3) nonprofits; organization must be serving in the same area as the facility from which they are requesting funds; organization must outline a specific need within the community and a plan on how to address it; grant also takes into account reputation', 'Spark Good nonprofits account, deed verification, Walmart account in the organization''s name, Verification of 501(c)(3)/public-charity eligibility, description of Volta and its work, description of the proposed project, explanation of the demonstrated community need, proposed use of grants funds, expected project outcomes, verification of compliance with Spark Good guidelines', '{}'::text[], 'Researching', '', '2026-08-23'::date),
  ('grant_sheet_24', 'pod_grants', 'CitizensNYC Community Leaders Grant', '', 'Novus', (SELECT id FROM public.team WHERE name='David Grinberg' AND deleted_at IS NULL LIMIT 1), 'Program', '2026-11-03'::date, '2026-02-02'::date, 'up to $5000', '', 'Projects that support economic development, education, and youth; specifically for nonprofits and grassroots volunteer groups; at least two volunteers; annual budget under $250,000; not promoting any religious or political ideology', 'Organization story including mission, accomplishments and ideally community-member testimonials, project outline, contact info, 501(c)(3) status, EIN if applicable, link to Form 990, if available, previous CitizensNYC funding history, outline of what a successful outcome would look like, project budget. EIN is needed.', '{}'::text[], 'Researching', '', '2026-08-23'::date),
  ('grant_sheet_25', 'pod_grants', 'Riley''s Way Foundation — Call For Kindness', '', 'Novus', (SELECT id FROM public.team WHERE name='David Grinberg' AND deleted_at IS NULL LIMIT 1), 'Call For Kindness | Join the Movement Today — Riley''s Way Foundation', NULL, NULL, 'up to $5000', '', 'Youth-led organizations(must be 13-23); projects aimed at making schools, communities, and neighborhoos "kinder"; specifically for projects that require not only funding, but also mentorship, as up to two fellows can be allocated as mentors for organizations;', 'Youth applicant information, oragnization/project information, the community issue being addressed, intended impact of the project, project implementation/growth plan, proposed use of funding, participation commitment for the year-long fellowship', '{}'::text[], 'Researching', 'Opens: Annual application cycle, 2027 date not yet announced
Deadline: 2026 fellows were announced on May 6, 2026', '2026-08-23'::date)
ON CONFLICT (id) DO NOTHING;

-- The workbooks sometimes use a link label rather than a URL. Keep that
-- reference searchable in notes instead of storing an invalid value in a URL
-- field. Bare domains are safe to normalize.
UPDATE public.grant_opportunities
SET url = 'https://' || url
WHERE id LIKE 'grant_sheet_%'
  AND url ~* '^[a-z0-9.-]+\.[a-z]{2,}(/.*)?$';

UPDATE public.grant_opportunities
SET notes = concat_ws(E'\n', nullif(notes, ''), 'Source reference: ' || url),
    url = ''
WHERE id LIKE 'grant_sheet_%'
  AND url <> ''
  AND url !~* '^https?://';

-- Imported means transcribed, not independently re-verified online.
UPDATE public.grant_opportunities
SET verified_on = NULL
WHERE id LIKE 'grant_sheet_%';

-- The workbook lists an opening of 2026-11-03 and a closing of 2026-02-02.
-- Preserve the discrepancy for review without presenting an impossible date.
UPDATE public.grant_opportunities
SET notes = concat_ws(E'\n', nullif(notes, ''), 'Source deadline was 2026-02-02; verify the next cycle.'),
    deadline = NULL
WHERE id = 'grant_sheet_24';
